### ISSUE TITLE
No longer works with Rhythmbox 2.97: TypeError: Argument 0 does not allow None as a value

### ISSUE THREAD

**Issue by hotice** [nvbn/rhythmbox-gmusic#17]
After the recent change that you've made to make this work with Rhythmbox 2.98 (and it now works with Rhythmbox 2.98, thanks!), the plugin no longer works with Rhythmbox 2.97.

Here's the output:

*\* (rhythmbox:2616): CRITICAL *_: syncdaemon_folder_info_get_subscribed: assertion `SYNCDAEMON_IS_FOLDER_INFO (finfo)' failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rhythmboxgmusic/**init**.py", line 293, in auth
    set_credentials(login, password)
  File "/usr/local/lib/python2.7/dist-packages/rhythmboxgmusic/**init**.py", line 56, in set_credentials
    GnomeKeyring.create_sync(KEYRING, None)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(_args, **kwargs)
TypeError: Argument 0 does not allow None as a value

**Comment by nvbn** [comment]
Hm, it works for me in Rhythmbox 2.97. Whate third-party ppa you use?

**Comment by hotice** [comment]
I've tried it both with Rhythmbox 2.97 from a PPA in Ubuntu 12.04 and with the official Rhythmbox 2.97 package from the Ubuntu repositories in Ubuntu 12.10...
