### ISSUE TITLE
Error when enabling plugin

### ISSUE THREAD

**Issue by jasoncawood** [nvbn/rhythmbox-gmusic#2]
I ran the install from the ppa and upon enabling the plugin I get this error

*\* (rhythmbox:3298): CRITICAL **: syncdaemon_folder_info_get_subscribed: assertion `SYNCDAEMON_IS_FOLDER_INFO (finfo)' failed

(rhythmbox:3298): GLib-CRITICAL **: g_variant_unref: assertion `value->ref_count > 0' failed
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/**init**.py", line 2, in <module>
    from gmusicapi.api import Api
ImportError: No module named gmusicapi.api

(rhythmbox:3298): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

**Comment by disparil** [comment]
Same installation procedure and same error.

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/__init__.py", line 2, in <module>
    from gmusicapi.api import Api
ImportError: No module named gmusicapi.api

(rhythmbox:4037): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'
```

I'm using Ubuntu 12.04 - 64bit.

**Comment by adrianojbr** [comment]
Same error here (Ubuntu 12.04 - 64bits):

adriano@Poderoso:~$ rhythmbox
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/**init**.py", line 2, in <module>
    from gmusicapi.api import Api
ImportError: No module named gmusicapi.api

(rhythmbox:23943): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

**Comment by ensonic** [comment]
Me too. Here is how to fix it:
sudo apt-get install python-pip
sudo pip install gmusicapi

**Comment by mmalmeida** [comment]
ensonic's details are needed for the plugin to work. This should be added to the docs.

**Comment by ensonic** [comment]
@mmalmeida I made a trivial patch. It is pending in the "pull requests" :/

**Comment by nvbn** [comment]
Pull request merge, i'll try to find some times for creating package for gmusicapi.

**Comment by ensonic** [comment]
@nvbn awesome & big thanks!
