### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by skribe** [nvbn/rhythmbox-gmusic#35]
Hi:

I'm on Ubuntu 13.04 64bit.  I get the following errors whenever I attempt to load the plugin. I've tried installing from both apt and pip.  Neither way seems to work.  

Rhythmbox: could not connect to socket
Rhythmbox: Connection refused
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rhythmboxgmusic/**init**.py", line 3, in <module>
    from gmusicapi import Webclient as Api
  File "/usr/lib/pymodules/python2.7/gmusicapi/**init**.py", line 9, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/pymodules/python2.7/gmusicapi/clients/**init**.py", line 1, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/lib/pymodules/python2.7/gmusicapi/clients/webclient.py", line 9, in <module>
    import gmusicapi.session
  File "/usr/lib/pymodules/python2.7/gmusicapi/session.py", line 7, in <module>
    import oauth2client
ImportError: No module named oauth2client

(rhythmbox:10360): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

**Comment by artyomszasa** [comment]
Same here (Ubuntu 13.04 AMD64, python-oauth2 installed):
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/**init**.py", line 3, in <module>
    from gmusicapi import Webclient as Api
  File "/usr/lib/pymodules/python2.7/gmusicapi/**init**.py", line 9, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/pymodules/python2.7/gmusicapi/clients/**init**.py", line 1, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/lib/pymodules/python2.7/gmusicapi/clients/webclient.py", line 9, in <module>
    import gmusicapi.session
  File "/usr/lib/pymodules/python2.7/gmusicapi/session.py", line 7, in <module>
    import oauth2client
ImportError: No module named oauth2client

When using "-d" also found following: (13:07:20)
[0x7ffde40042c0] [<module>] /usr/lib/pymodules/python2.7/gmusicapi/compat.py:30: warning: could not import appdirs; will use current directory

**Comment by ezequielfalcon** [comment]
Same here, Ubuntu 13.10 AMD64, same log.

**Comment by danielfn** [comment]
Installing the python-google-oauth2client package solves the loading issue. I got it from here: http://code.google.com/p/google-api-python-client/downloads/list

**Comment by clschnei** [comment]
@danielfn thanks for the solution!

ps - @nvbn Should this package not included in the with the library/README instructions?

**Comment by erichlf** [comment]
Github needs a +1 feature for comments. @danielfn you are the man (or woman)!
