### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by boxman0617** [nvbn/rhythmbox-gmusic#38]
Plugin shows up on the Plugins section and I can enable it. Once I add my username and password, and I click "Ok" it does nothing...

**Comment by Rleahy22** [comment]
+1

**Comment by alexfigueiredo** [comment]
+1

**Comment by Nxt3** [comment]
Same. If it helps, I have two-step authentication enabled on my Google account.

**Comment by slifin** [comment]
+1 also have two step authentication

Generating a application specific password for rhythm box does not appear to help

Updated with trace back:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/**init**.py", line 295, in auth
    self.init_authenticated()
  File "/usr/lib/pymodules/python2.7/rhythmboxgmusic/**init**.py", line 320, in init_authenticated
    playlists = api.get_all_playlist_ids()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 390, in get_all_playlist_ids
    res = self._make_call(webclient.GetPlaylistSongs, 'all')
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetPlaylistSongs: 404 Client Error: Not Found
(requests kwargs: {'url': 'https://play.google.com/music/services/loadplaylist', 'headers': {'Authorization': '<omitted>'}, 'data': {'json': '{}'}, 'method': 'POST', 'params': {'u': 0, 'xt': 'CjUKATASMEFNLVdiWGhjUlZrMHh0ajNLbnFPN0ZiNU81OGVPM1VOdWc6MTM5OTIwNzQzODg4MA=='}})

I would assume part of google's API has changed because of the 404? 

https://play.google.com/music/services/loadalltracks also appears to 404

**Comment by immartian** [comment]
same here

Successfully logged in.

Loading library...
Traceback (most recent call last):
  File "gm.py", line 66, in <module>
    demonstration()
  File "gm.py", line 42, in demonstration
    library = api.get_all_songs()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 312, in get_all_songs
    to_return = [song for chunk in to_return for song in chunk]
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 324, in _get_all_songs
    lib_chunk['continuationToken'])
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 225, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: GetLibrarySongs: 404 Client Error: Not Found
(requests kwargs: {'url': 'https://play.google.com/music/services/loadalltracks', 'headers': {'Authorization': '<omitted>'}, 'data': {'json': '{}'}, 'method': 'POST', 'params': {'u': 0, 'xt': 'CjUKATASMEFNLVdiWGhsSGZrUHltSkdZN2JKTW10b2d5WWEzVnlnZUE6MTQwMTI4ODYwNDE2MA=='}})

**Comment by samhed** [comment]
I'm having the same problem. I know this was more than 2 years ago, but did any of you manage to find a solution?

**Comment by samhed** [comment]
An app-specific password worked for me!
