### ISSUE TITLE
The plugin 'Google play Music Plugin' could not be loaded

### ISSUE THREAD

**Issue by XoneX** [nvbn/rhythmbox-gmusic#50]
Ubuntu 14.04 with Rhythmbox 2.99.1.
What Happens? :_(

**Comment by p0lar-bear** [comment]
@XoneX, we need more info. Make sure that the plugin is unchecked in your plugins list, then close rhythmbox entirely (stop any music playing and close it) and open a terminal window. Type "rhythmbox" into the prompt and hit enter. Try to enable the plugin again and then paste your terminal output here.

**Comment by XoneX** [comment]
http://i.imgur.com/MfQt84x.png

**Comment by p0lar-bear** [comment]
Erm... no, I'm loking for terminal output. Like so:

![image](https://cloud.githubusercontent.com/assets/4573881/3399219/bbdc03de-fd39-11e3-8f92-7f45fff7766a.png)

Again, please disable the plugin, stop all playback, close rhythmbox, and then open it again in a terminal. Copy and paste (or screenshot) the output in the terminal window.

**Comment by XoneX** [comment]
xonex@ubuntuX:~$ rhythmbox
ERROR:root:Could not find any typelib for GConf
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rhythmboxgmusic/**init**.py", line 1, in <module>
    from gi.repository import (GObject, Peas, Gtk, GConf, RB, GLib,
ImportError: cannot import name GConf

(rhythmbox:3357): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

(rhythmbox:3357): Gtk-WARNING **: mnemonic "b" wasn't removed for widget (0xbb6b70)

**Comment by p0lar-bear** [comment]
Apologies for the late reply, I've been busy as all get out lately.

How did you install gmusic? That message indicates that you're missing the GConf module for python.

**Comment by paulhewson** [comment]
Sorry if I sneak into this conversation but I have the same issue here. The terminal says

```
(rhythmbox:8159): libpeas-WARNING **: Error importing plugin 'rhythmboxgmusic':
Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rhythmboxgmusic'

(rhythmbox:8159): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

(rhythmbox:8159): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed

(rhythmbox:8159): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed
```

I installed the plugin via python-pip as described. I'm using Rhythmbox 3.4 on debian; the funny thing is that I installed the plugin in arch, same version of rb, same python-pip and it works
