### ISSUE TITLE
Can't install rhythmbox-gmusic on Fedora 22

### ISSUE THREAD

**Issue by robinhood2014** [nvbn/rhythmbox-gmusic#58]
I can't seem to install this plugin on Fedora 22. It gives me what seems to be success messages, but then, out of nowhere, a traceback and then a fatal error, like this:

Collecting rhythmbox-gmusic from git+https://github.com/nvbn/rhythmbox-gmusic.git#egg=rhythmbox-gmusic
  Cloning https://github.com/nvbn/rhythmbox-gmusic.git to /tmp/pip-build-RDLzuE/rhythmbox-gmusic
Collecting gmusicapi (from rhythmbox-gmusic)
  Using cached gmusicapi-7.0.0.tar.gz
Collecting futures (from rhythmbox-gmusic)
  Downloading futures-3.0.3-py2-none-any.whl
Collecting validictory!=0.9.2,>=0.8.0 (from gmusicapi->rhythmbox-gmusic)
  Downloading validictory-1.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.1 in /usr/lib/python2.7/site-packages (from gmusicapi->rhythmbox-gmusic)
Collecting mutagen>=1.18 (from gmusicapi->rhythmbox-gmusic)
  Downloading mutagen-1.31.tar.gz (897kB)
    100% |████████████████████████████████| 901kB 160kB/s 
Collecting protobuf>=2.4.1 (from gmusicapi->rhythmbox-gmusic)
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |████████████████████████████████| 188kB 515kB/s 
    Complete output from command python setup.py egg_info:

```
Installed /tmp/pip-build-RDLzuE/protobuf/.eggs/google_apputils-0.4.2-py2.7.egg
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-build-RDLzuE/protobuf/setup.py", line 200, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1074, in best_match
    dist = working_set.find(req)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 711, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (pytz 2012d (/usr/lib/python2.7/site-packages), Requirement.parse('pytz>=2010'))

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RDLzuE/protobuf

What's wrong here?

**Comment by mbethke** [comment]
I just ran into the same problem while trying to install protobuf-2.6.1, also on F22. The problem is that pip 6.0.8 seems to have a problem parsing pytz's version number "2012d". This has been fixed in the latest pip 7.1.2, so this works:

``` bash
$ pip install --user --upgrade pip
$ PATH="$HOME/.local/bin:$PATH"
$ pip install --user --upgrade ... 
```

**Comment by agunn-mc** [comment]
I was having this same issue with pip 7.1.2 on F22. I was able to work around it by installing protobuf with easy_install.

```
$ sudo easy_install protobuf
```

**Comment by samhed** [comment]
Can't install on Fedora 24.. I'm getting:

```
Compiling support for Intel AES instructions
building 'Crypto.Hash._MD2' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLTC_NO_ASM -DHAVE_CPUID_H -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o
gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/src/MD2.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD2.so
/bin/ld: cannot find -lpython2.7
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-JXgtcF/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vuzHx9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-JXgtcF/pycryptodomex/
```

**Comment by KeizerDev** [comment]
@samhed
You should install `python-devel` to compile with it.

```
sudo dnf install python-devel-2.7.12-6.fc24 
```

**Comment by samhed** [comment]
thanks @KeizerDev

**Comment by rimmer** [comment]
gratefull @KeizerDev as well

**Comment by fkaleo** [comment]
This fork seems more up to date: https://github.com/jgoguen/rhythmbox-gmusic
