### ISSUE TITLE
Ubuntu 17.10 and the plugin

### ISSUE THREAD

**Issue by ghost** [nvbn/rhythmbox-gmusic#64]
Hi,

I'm trying to install the plugin using `pip3`
The installation completes successfully without throwing any errors.
But when I open Rhythmbox and try to enable this plugin, Rhythmbox crashes.
Please help. Is there a way to troubleshoot this issue and find the real problem.

Edit: I started Rhythmbox in debug mode. When I try to enable this plugin(while in debug mode), I get an error stating that my 'This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.'
I have installed protobuf 3.5.0 but I still keep getting this error. This is the latest version for protobuf(I mean the latest is 3.5.1 but still) and I have also have the latest version for protobuf-compiler(v 3.0)

**Comment by mark-ignacio** [comment]
You can solve this all by removing the pip3-installed versions and installing the one from apt. This worked for me:

```
# pip3 uninstall protobuf
# apt install python3-protobuf
```

I haven't bothered to figure out how to install things properly in the first place.

**Comment by ghost** [comment]
@mark-ignacio I have already tried that. It didn't work.
I'm not a coder unless I know how to use google isn't that how it goes. :laughing:   

PS I tried it again now it didn't work(since you said it worked for you). `apt install python3-protobuf` installs v3.0.0-9ubuntu5 for me

**Comment by LoveMHz** [comment]
Here's the console output for me on Ubuntu 17.10

```
(rhythmbox:19343): libpeas-WARNING **: Error importing plugin 'rhythmboxgmusic':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rhythmboxgmusic'

(rhythmbox:19343): libpeas-WARNING **: Error loading plugin 'rhythmboxgmusic'

(rhythmbox:19343): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed

(rhythmbox:19343): libpeas-CRITICAL **: peas_engine_create_extensionv: assertion 'peas_plugin_info_is_loaded (info)' failed
```

**Comment by fkaleo** [comment]
This fork seems more up to date: https://github.com/jgoguen/rhythmbox-gmusic
